config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_up', to: 'users/registrations#new'
    delete 'sign_out', to: 'users/sessions#destroy'
  end

  get '/courses.delete' => 'courses#destroy'

  resources :courses do
    collection do
      post 'enlist', as: :enlist
    end
  end
  resources :moderators

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def home_controller?
    params[:controller] == 'home'
  end

  def render_user_homepage
    if current_user.student?
      content_tag(:div, 'Student')
    elsif current_user.moderator?
      content_tag(:div, 'Moderator')
    elsif current_user.professor?
      content_tag(:div, 'Professor')
    elsif current_user.administrator?
      content_tag(:div, 'Administrator')
    end
  end
end

app/views/home/_form.html.slim
h2 Log in

= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f|
  .field
    = f.label :email
    br /
    = f.email_field :email, autofocus: true 

  .field
    = f.label :password 
    br /
    = f.password_field :password, autocomplete: 'off'

  - if devise_mapping.rememberable?
    .field
      = f.check_box :remember_me
      = f.label :remember_me

  .actions
    = f.submit 'Log in' 

= render 'users/shared/links'

app/views/home/index.html.slim
- if user_signed_in? 
  = render_user_homepage