config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_up', to: 'users/registrations#new'
    delete 'sign_out', to: 'users/sessions#destroy'
  end

  get '/courses.delete' => 'courses#destroy'

  resources :courses do
    collection do
      post 'enlist', as: :enlist
    end
  end
  resources :moderators

end

app/models/moderator.rb
class Moderator < User
  def send_moderator_confirmation_instructions(options)
    send_confirmation_instructions(options)
  end
end

app/controllers/moderators_controller.rb
class ModeratorsController < ApplicationController
  before_action :authenticate_user!

  def new
    @moderator = Moderator.new
  end

  def index
    @moderators = Moderator.all
  end

  def create
    #generate random password_token
    password_token = Devise.friendly_token.first(8)
    
    @moderator = Moderator.new(moderator_params(password_token))

    if @moderator.save
      # manually send the confirmation instructions for moderators
      @moderator.send_moderator_confirmation_instructions(
        {moderator: true, 
        password_token: password_token})
      flash[:notice] = 'Moderator account added. Confirmation email sent'
      redirect_to moderators_path
    else 
      flash.now[:error] = 'Error in creating modearator account'
      render 'new'
    end
  end

  def destroy
    @moderator = Moderator.find(params[:id])
    @moderator.delete
    redirect_to moderators_path
  end

  private

  def moderator_params(password_token)
    # set the password field of the moderator account to the
    # random password_token

    moderator_params = {username: params[:moderator][:username],
                        email: params[:moderator][:email],
                        password: password_token,
                        password_confirmation: password_token}
    moderator_params
  end
end

app/helpers/moderators_helper.rb
module ModeratorsHelper
end

app/views/moderators/index.html.slim
table
  thead
    tr
      th username
      th email
      th colspan='2'
  tbody
    - @moderators.each do |moderator|
      tr
        td = moderator.username
        td = moderator.email
        td = link_to 'Show', '#'
        td = link_to 'Delete', moderator_path(id: moderator.id), \
          method: :delete, data: {confirm: 'Are you sure?'}

= link_to 'Add Moderator Account', new_moderator_path

app/views/moderators/new.html.slim
= form_for :moderator, url: moderators_path do |f|
  p
    = f.label :username
    br
    = f.text_field :username

  p
    = f.label :email
    br
    = f.email_field :email

  p
   = f.submit 'Add Moderator Account'