config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_up', to: 'users/registrations#new'
    delete 'sign_out', to: 'users/sessions#destroy'
  end

  get '/courses.delete' => 'courses#destroy'

  resources :courses do
    collection do
      post 'enlist', as: :enlist
    end
  end
  resources :moderators

end

app/views/layouts/_flash_messages.html.slim
.row
  - flash.each do |name, msg|
    - if msg.is_a?(String)
      #flash-messages.alert-box.small-8.columns.small-centered.round class='#{flash_style(name)}'
        = content_tag :div, msg

app/views/layouts/_navbar.html.slim
nav.top-bar data-topbar='' role='navigation'
  ul.title-area
    li.name
      h1
        = link_to 'IEEE', root_path

  section.top-bar-section
    ul.left
      = render 'layouts/user_tabs'
    
    ul.right
      - if user_signed_in?
        li.active
          = link_to 'Sign out', sign_out_path, method: :delete
      - else
        li.active
          = link_to 'Log in', sign_in_path

app/views/layouts/_user_tabs.html.slim
- if user_signed_in?
  - if current_user.administrator?
    li
      = link_to 'Moderators', moderators_path 
  - elsif current_user.moderator?
    li
      = link_to 'Courses', courses_path
  - elsif current_user.student?
    li
      = link_to 'Courses', courses_path
  - elsif current_user.professor?

app/views/layouts/application.html.slim
doctype html
html lang='en'
  head
    meta charset='utf-8' /
    meta name='viewport' content='width=device-width, initial-scale=1.0' /

    title 
      = content_for?(:title) ? yield(:title) : 'IEEEVideoLectureSeries'

    = stylesheet_link_tag    'application'
    = javascript_include_tag 'vendor/modernizr'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    = render 'layouts/navbar'
    = render 'layouts/flash_messages'
    = yield